name: my first workflow

on: push

jobs:
    first_job: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Read files
          run: |
               echo " Myfirst action"
               ls -ltra
               cat README.md

      