name: my first workflow

on: push

jobs:
    first_job: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Welcome Message
          run: echo " Myfirst action"

        - name: List files
          run: ls

        - name: Read file
          run: cat README.md  