name: Generate ASCII Artwork

on:
  push

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

      - name: sleep for 30 seconds
        run: sleep 30

  test:
    needs: build_job
    runs-on: ubuntu-latest
    steps:
      - name: sleep for 30 seconds
        run: sleep 30
  
      - name: Test File Exists
        run: grep -i "dragon" dragon.txt
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Read file
        run: cat dragon.txt
      - name: Deploy
        run:  echo " Deploying........."
      


